// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQuat7ibujoHcr1t34IpkxKcAdQpowkV8',
    appId: '1:865266945515:web:3d4dc41a83a367ca005dae',
    messagingSenderId: '865266945515',
    projectId: 'skyflight-a2e08',
    authDomain: 'skyflight-a2e08.firebaseapp.com',
    storageBucket: 'skyflight-a2e08.appspot.com',
    measurementId: 'G-G2YK8FSNCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8xpPWnx6K-H_1WQmv9IMOTApBNgiEx0',
    appId: '1:865266945515:android:7c624f72f56405d6005dae',
    messagingSenderId: '865266945515',
    projectId: 'skyflight-a2e08',
    storageBucket: 'skyflight-a2e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TK-fODyJQonwUbuRINFAv7rpa60rJXg',
    appId: '1:865266945515:ios:68f37cf92d2f235d005dae',
    messagingSenderId: '865266945515',
    projectId: 'skyflight-a2e08',
    storageBucket: 'skyflight-a2e08.appspot.com',
    iosClientId: '865266945515-5v7ap772q1cctkn1lqvb9jgvm6klq64b.apps.googleusercontent.com',
    iosBundleId: 'com.gdsc.skyflight',
  );
}
